//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWPIO.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Controllers_HomeController {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Controllers_HomeController() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CWPIO.Resources.Controllers.HomeController", typeof(Controllers_HomeController).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email already subscribed!.
        /// </summary>
        internal static string Subscribe_EmailExist {
            get {
                return ResourceManager.GetString("Subscribe_EmailExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;&lt;head&gt;&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        ///&lt;meta name=&quot;viewport&quot; content=&quot;initial-scale=1.0&quot;&gt;
        ///&lt;meta name=&quot;format-detection&quot; content=&quot;telephone=no&quot;&gt;
        ///&lt;title&gt;{0}&lt;/title&gt;
        ///&lt;style type=&quot;text/css&quot;&gt;.socialLinks {{font-size: 6px;}}
        ///.socialLinks a {{display: inline-block;}}
        ///.socialIcon {{display: inline-block;vertical [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Subscribe_Mail_Html {
            get {
                return ResourceManager.GetString("Subscribe_Mail_Html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}
        ///{1}
        ///{2}
        ///{3}
        ///{5}: {4}.
        /// </summary>
        internal static string Subscribe_Mail_Text {
            get {
                return ResourceManager.GetString("Subscribe_Mail_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field email required.
        /// </summary>
        internal static string Subscribe_NoEmail {
            get {
                return ResourceManager.GetString("Subscribe_NoEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field name required.
        /// </summary>
        internal static string Subscribe_NoName {
            get {
                return ResourceManager.GetString("Subscribe_NoName", resourceCulture);
            }
        }
    }
}
