//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWPIO.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Services_EmailSender {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Services_EmailSender() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CWPIO.Resources.Services.EmailSender", typeof(Services_EmailSender).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CryptoWorkPlace Token Sale Team.
        /// </summary>
        internal static string Subscribe_Footer {
            get {
                return ResourceManager.GetString("Subscribe_Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;&lt;head&gt;&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        ///&lt;meta name=&quot;viewport&quot; content=&quot;initial-scale=1.0&quot;&gt;
        ///&lt;meta name=&quot;format-detection&quot; content=&quot;telephone=no&quot;&gt;
        ///&lt;title&gt;{0}&lt;/title&gt;
        ///&lt;style type=&quot;text/css&quot;&gt;.socialLinks {font-size: 6px;}
        ///.socialLinks a {display: inline-block;}
        ///.socialIcon {display: inline-block;vertical-alig [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Subscribe_Mail_Html {
            get {
                return ResourceManager.GetString("Subscribe_Mail_Html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}
        ///{1}
        ///{2}
        ///{3}
        ///{5}: {4}.
        /// </summary>
        internal static string Subscribe_Mail_Text {
            get {
                return ResourceManager.GetString("Subscribe_Mail_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email sent to .
        /// </summary>
        internal static string Subscribe_Mailto_Text {
            get {
                return ResourceManager.GetString("Subscribe_Mailto_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We`ll be sharing important information with you, feel free to check out the website for frequent updates..
        /// </summary>
        internal static string Subscribe_Paragraph_One {
            get {
                return ResourceManager.GetString("Subscribe_Paragraph_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have indicated that you are interested in purchasing over $1000 in CWT-P tokens with assured allocation, you can join our pre-sale. Please write us how much you want to spend. A member of our team will contact you via email shortly with details. We`ll be processing pre-sale / pre-funding requests starting on January 1th through to February 15th, depending on availability, and may choose to limit or suspend depending on demand..
        /// </summary>
        internal static string Subscribe_Paragraph_Two {
            get {
                return ResourceManager.GetString("Subscribe_Paragraph_Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CryptoWorkPlace Token Presale.
        /// </summary>
        internal static string Subscribe_Subject {
            get {
                return ResourceManager.GetString("Subscribe_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CryptoWorkPlace.
        /// </summary>
        internal static string Subscribe_Title {
            get {
                return ResourceManager.GetString("Subscribe_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for signing up to receive updates from the CryptoWorkPlace Token Presale!.
        /// </summary>
        internal static string Subscribe_Topic {
            get {
                return ResourceManager.GetString("Subscribe_Topic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsubscribe.
        /// </summary>
        internal static string Subscribe_Unsubscribe_Text {
            get {
                return ResourceManager.GetString("Subscribe_Unsubscribe_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View in your browser.
        /// </summary>
        internal static string Subscribe_View_Browser {
            get {
                return ResourceManager.GetString("Subscribe_View_Browser", resourceCulture);
            }
        }
    }
}
