//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWPIO.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CWPIO.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ONE PAGE.
        /// </summary>
        internal static string _1page {
            get {
                return ResourceManager.GetString("1page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50% OF TOTAL.
        /// </summary>
        internal static string _50part {
            get {
                return ResourceManager.GetString("50part", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADVISERS.
        /// </summary>
        internal static string adv {
            get {
                return ResourceManager.GetString("adv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alexander Podelko.
        /// </summary>
        internal static string Alexander_Podelko {
            get {
                return ResourceManager.GetString("Alexander Podelko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alexey Gladkov.
        /// </summary>
        internal static string Alexey_Gladkov {
            get {
                return ResourceManager.GetString("Alexey Gladkov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alexey Lykov.
        /// </summary>
        internal static string Alexey_Lykov {
            get {
                return ResourceManager.GetString("Alexey Lykov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AMAZING FEATURES.
        /// </summary>
        internal static string amfeac {
            get {
                return ResourceManager.GetString("amfeac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anton Maslov.
        /// </summary>
        internal static string Anton_Maslov {
            get {
                return ResourceManager.GetString("Anton Maslov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anton Polyansky.
        /// </summary>
        internal static string Anton_Polyansky {
            get {
                return ResourceManager.GetString("Anton Polyansky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to April.
        /// </summary>
        internal static string april {
            get {
                return ResourceManager.GetString("april", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artur Enokyan.
        /// </summary>
        internal static string Artur_Enokyan {
            get {
                return ResourceManager.GetString("Artur Enokyan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AWESOME &lt;span class=&quot;bold&quot;&gt;PERFORMANCE&lt;/span&gt;.
        /// </summary>
        internal static string awsperf {
            get {
                return ResourceManager.GetString("awsperf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BUILT-IN &lt;span class=&quot;bold&quot;&gt;CRYPTO-STORAGE&lt;/span&gt;.
        /// </summary>
        internal static string buildin {
            get {
                return ResourceManager.GetString("buildin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEO.
        /// </summary>
        internal static string ceo {
            get {
                return ResourceManager.GetString("ceo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        internal static string contacts {
            get {
                return ResourceManager.GetString("contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CTO.
        /// </summary>
        internal static string cto {
            get {
                return ResourceManager.GetString("cto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CVO.
        /// </summary>
        internal static string cvo {
            get {
                return ResourceManager.GetString("cvo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decentralized system.
        /// </summary>
        internal static string decentralizedsystem {
            get {
                return ResourceManager.GetString("decentralizedsystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CWP is a decentralized ecosystem based on a blockchain technology that includes a
        ///Micro-PC that enables applications to run in a secure, isolated environment, special
        ///software, a set of web portal services designed to organize protection against threats
        ///on the network, and a distributed registry of statuses.
        /// </summary>
        internal static string decentrsys {
            get {
                return ResourceManager.GetString("decentrsys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denis Kuznetsov.
        /// </summary>
        internal static string Denis_Kuznetsov {
            get {
                return ResourceManager.GetString("Denis Kuznetsov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EARLY BIRDS DISCOUNTS.
        /// </summary>
        internal static string disc {
            get {
                return ResourceManager.GetString("disc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOCUMENTS.
        /// </summary>
        internal static string documents {
            get {
                return ResourceManager.GetString("documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to downloads.
        /// </summary>
        internal static string downloads {
            get {
                return ResourceManager.GetString("downloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En.
        /// </summary>
        internal static string en {
            get {
                return ResourceManager.GetString("en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exploit.
        /// </summary>
        internal static string exploit {
            get {
                return ResourceManager.GetString("exploit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Взлом.
        /// </summary>
        internal static string hack {
            get {
                return ResourceManager.GetString("hack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hard cap.
        /// </summary>
        internal static string hcap {
            get {
                return ResourceManager.GetString("hcap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to based on a personal computer the size of a USB flash drive.
        /// </summary>
        internal static string head {
            get {
                return ResourceManager.GetString("head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head of Hardware Production.
        /// </summary>
        internal static string Head_of_Hardware_Production {
            get {
                return ResourceManager.GetString("Head of Hardware Production", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CryptoWorkPlace Micro-PC is not only a secure key storage, it is a fully independent PC with an operating system and applications.
        /// </summary>
        internal static string head_sub {
            get {
                return ResourceManager.GetString("head sub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string icape {
            get {
                return ResourceManager.GetString("icape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string icape1 {
            get {
                return ResourceManager.GetString("icape1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The idea of a microcomputer.
        /// </summary>
        internal static string idea {
            get {
                return ResourceManager.GetString("idea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string kcells {
            get {
                return ResourceManager.GetString("kcells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string kcells1 {
            get {
                return ResourceManager.GetString("kcells1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead Mathematician.
        /// </summary>
        internal static string Lead_Mathematician {
            get {
                return ResourceManager.GetString("Lead Mathematician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string looses {
            get {
                return ResourceManager.GetString("looses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        internal static string mail {
            get {
                return ResourceManager.GetString("mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to March.
        /// </summary>
        internal static string march {
            get {
                return ResourceManager.GetString("march", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maxim Maslich.
        /// </summary>
        internal static string Maxim_Maslich {
            get {
                return ResourceManager.GetString("Maxim Maslich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h4&gt;Meet Our&lt;/h4&gt;&lt;h2&gt;TEAM&lt;/h2&gt;.
        /// </summary>
        internal static string meet {
            get {
                return ResourceManager.GetString("meet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAX. EMISSION OF TOKENS.
        /// </summary>
        internal static string memiss {
            get {
                return ResourceManager.GetString("memiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participate *.
        /// </summary>
        internal static string participate {
            get {
                return ResourceManager.GetString("participate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participate in the Token Sale.
        /// </summary>
        internal static string particsale {
            get {
                return ResourceManager.GetString("particsale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partners.
        /// </summary>
        internal static string partners {
            get {
                return ResourceManager.GetString("partners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patenting.
        /// </summary>
        internal static string pat {
            get {
                return ResourceManager.GetString("pat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phishing.
        /// </summary>
        internal static string phishing {
            get {
                return ResourceManager.GetString("phishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PREVENTING MELTDOWN &amp;amp; &lt;span class=&quot;bold&quot;&gt;SPECTRE ATTACKS&lt;/span&gt;.
        /// </summary>
        internal static string prevmelt {
            get {
                return ResourceManager.GetString("prevmelt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blockchain &lt;br&gt;&lt;span&gt;Problem&lt;/span&gt;.
        /// </summary>
        internal static string problem {
            get {
                return ResourceManager.GetString("problem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRODUCT.
        /// </summary>
        internal static string product {
            get {
                return ResourceManager.GetString("product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string qa {
            get {
                return ResourceManager.GetString("qa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product version 1.0 for system administrators.
        /// </summary>
        internal static string r1 {
            get {
                return ResourceManager.GetString("r1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing of the product in independent laboratories.
        /// </summary>
        internal static string r10 {
            get {
                return ResourceManager.GetString("r10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q2-Q3.
        /// </summary>
        internal static string r11 {
            get {
                return ResourceManager.GetString("r11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The start of mass production and launching of technical support services.
        /// </summary>
        internal static string r12 {
            get {
                return ResourceManager.GetString("r12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q4.
        /// </summary>
        internal static string r13 {
            get {
                return ResourceManager.GetString("r13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The start of sales in USA, Europe and Asian markets.
        /// </summary>
        internal static string r14 {
            get {
                return ResourceManager.GetString("r14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product version 2.0 thin client.
        /// </summary>
        internal static string r2 {
            get {
                return ResourceManager.GetString("r2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product version 3.0 VPN client and the access key to the medical database.
        /// </summary>
        internal static string r3 {
            get {
                return ResourceManager.GetString("r3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product version 4.0 a researcher&apos;s workplace for access to remote knowledge bases.
        /// </summary>
        internal static string r4 {
            get {
                return ResourceManager.GetString("r4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product version 5.0 portable workplace with business and gaming applications.
        /// </summary>
        internal static string r5 {
            get {
                return ResourceManager.GetString("r5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product version 6.0 portable workstation oriented to client-server applications.
        /// </summary>
        internal static string r6 {
            get {
                return ResourceManager.GetString("r6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating a CryptoWorkPlace concept.
        /// </summary>
        internal static string r7 {
            get {
                return ResourceManager.GetString("r7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token Pre-Sale.
        /// </summary>
        internal static string r8 {
            get {
                return ResourceManager.GetString("r8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token Sale, Launching of the Web Portal beta.
        /// </summary>
        internal static string r9 {
            get {
                return ResourceManager.GetString("r9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Please register to participate in our ICO! After registration please also check your Spam/Promotion email folder..
        /// </summary>
        internal static string reghelp {
            get {
                return ResourceManager.GetString("reghelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to According to a Chainalysis
        ///                            &lt;a href=&quot;https://blog.chainalysis.com/the-rise-of-cybercrime-on-ethereum/&quot; target=&quot;_blank&quot;&gt;report&lt;/a&gt;
        ///                            &lt;br&gt;
        ///                            the world is seeing a meteoric rise in cybercrime targeting ICOs. In June 2017 alone&lt;br&gt;
        ///                            investors loses from such actions reached $100M while in August they were above&lt;br&gt;
        ///                            &lt;strong&gt;$220M&lt;/strong&gt;..
        /// </summary>
        internal static string report {
            get {
                return ResourceManager.GetString("report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to report.
        /// </summary>
        internal static string reportlink {
            get {
                return ResourceManager.GetString("reportlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROADMAP.
        /// </summary>
        internal static string roadmap {
            get {
                return ResourceManager.GetString("roadmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROAD&lt;span&gt;MAP&lt;/span&gt;.
        /// </summary>
        internal static string roadmaph {
            get {
                return ResourceManager.GetString("roadmaph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROUND OF TOKEN PRE-SALE.
        /// </summary>
        internal static string round {
            get {
                return ResourceManager.GetString("round", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ru.
        /// </summary>
        internal static string ru {
            get {
                return ResourceManager.GetString("ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruslan Pichugin.
        /// </summary>
        internal static string Ruslan_Pichugin {
            get {
                return ResourceManager.GetString("Ruslan Pichugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NUMBER OF TOKENS FOR SALE.
        /// </summary>
        internal static string sailingt {
            get {
                return ResourceManager.GetString("sailingt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOKEN &lt;span&gt;SALE&lt;/span&gt;.
        /// </summary>
        internal static string sale {
            get {
                return ResourceManager.GetString("sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senior System Analyst.
        /// </summary>
        internal static string Senior_System_Analyst {
            get {
                return ResourceManager.GetString("Senior System Analyst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software Engineer.
        /// </summary>
        internal static string Software_Engineer {
            get {
                return ResourceManager.GetString("Software Engineer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CWP is the &lt;br&gt;&lt;span&gt;solution&lt;/span&gt;.
        /// </summary>
        internal static string solution {
            get {
                return ResourceManager.GetString("solution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRICE OF THE TOKEN.
        /// </summary>
        internal static string tc {
            get {
                return ResourceManager.GetString("tc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        internal static string team {
            get {
                return ResourceManager.GetString("team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOGGLE TOKEN CODE.
        /// </summary>
        internal static string toggle {
            get {
                return ResourceManager.GetString("toggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOKEN.
        /// </summary>
        internal static string token {
            get {
                return ResourceManager.GetString("token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up to.
        /// </summary>
        internal static string up2 {
            get {
                return ResourceManager.GetString("up2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wagan Sarukhanov.
        /// </summary>
        internal static string Wagan_Sarukhanov {
            get {
                return ResourceManager.GetString("Wagan Sarukhanov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet soon on.
        /// </summary>
        internal static string wallet {
            get {
                return ResourceManager.GetString("wallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WHITE PAPER.
        /// </summary>
        internal static string wp {
            get {
                return ResourceManager.GetString("wp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YEAR.
        /// </summary>
        internal static string year {
            get {
                return ResourceManager.GetString("year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yoji Kishi.
        /// </summary>
        internal static string Yoji_Kishi {
            get {
                return ResourceManager.GetString("Yoji Kishi", resourceCulture);
            }
        }
    }
}
